[package]
name = "drem"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "derive"] }
git2 = "0.19.0"
zip = "2.2.0"
